### ISSUE TITLE
0.1.3 crash report

### ISSUE THREAD

**Issue by EthanO3O** [GenDeathrow/CutScenes-1.7.10#1]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 16-2-24 下午2:10
Description: Unexpected error

java.lang.RuntimeException: java.io.FileNotFoundException: ccsfiles:textures/gui/102_105_114_101.gif
    at com.gendeathrow.cutscene.client.render.AnimTexture.<init>(AnimTexture.java:148)
    at com.gendeathrow.cutscene.SceneRender.ActorObject.init(ActorObject.java:163)
    at com.gendeathrow.cutscene.SceneRender.SegmentObject.init(SegmentObject.java:38)
    at com.gendeathrow.cutscene.SceneRender.SceneObject.init(SceneObject.java:52)
    at com.gendeathrow.cutscene.client.gui.CutSceneGui.func_73866_w_(CutSceneGui.java:70)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
    at com.gendeathrow.cutscene.client.ClientTickHandler.RenderTickEvent(ClientTickHandler.java:55)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_ClientTickHandler_RenderTickEvent_RenderTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:117)
Caused by: java.io.FileNotFoundException: ccsfiles:textures/gui/102_105_114_101.gif
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:71)
    at com.gendeathrow.cutscene.client.render.AnimTexture.<init>(AnimTexture.java:90)
    ... 25 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows XP (x86) version 5.1
    Java Version: 1.7.0_80, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 102126184 bytes (97 MB) / 231718912 bytes (220 MB) up to 825491456 bytes (787 MB)
    JVM Flags: 5 total; -Xincgc -Xmx800m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJA  cutscene{0.1.3} [Custom Cutscenes](CustomCutScene-1.7.10-0.1.3%281%29.jar) 
    GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 6.14.10.5449' Renderer: 'Intel(R) HD Graphics'
    Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 6.14.10.5449, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: 简体中文 (中国)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by GenDeathrow** [comment]
So the file is missing.. try this first , 

make sure all files are in your "custom-cutscene-files" folder, 

than go to the config file, set "B:Reload_Assets_On_Load" to true.

than run game, after its finished loading, shut down and start game again. It should show.

http://minecraft.curseforge.com/projects/custom-cutscenes-splashscreen/pages/custom-cutscenes/creating-your-first-cutscene

if it doesn't work. zip your "custom-cutscene-files" + "config/CustomCutScenes" folder +  "mods/custom_cutscene_files.jar", and give me a link for it ,and I will take a look at it. 

EDIT: I haven't really added this on the site tutorial page yet.. after you build the file, you can technically delete everything in the "custom-cutscene-files" folder, or not include it in the mod pack.  Everything you need is in the "custom-cutscene-files.jar" file in your mod folder. that will cut down on the size of your mod pack. These are alot of things that will be addressed before a release version is made

**Comment by GenDeathrow** [comment]
@EthanJJC Any luck on this issue yet?

**Comment by EthanO3O** [comment]
I try your advice ,and download the "custom_cutscene_files.jar"
But there is nothing in custom-cutscene-files
my forge version is 1558

**Comment by GenDeathrow** [comment]
are you trying to just view the demo I had created or are you making your own cutscene? Whats your OS? if nothing is in custom-cutscene-files folder.. than you will get an error after you build the jar file.

**Comment by EthanO3O** [comment]
Win XP 
is it too old?

**Comment by EthanO3O** [comment]
i remember first time i see sth in custom-cutscene-files 
But now have nothing
still can't join game  the client crashed at last

**Comment by GenDeathrow** [comment]
Try backing up any of your config files, and than delete your config files. the start the game up again. it will regenerate all files. WinXp shouldn't be too old. and if you have custom-cutscene-files folder delete it.

In theory this is whats suppose to happen. 
1. when you have Dev version set to true and your missing "custom-cutscene-files" folder & config folder it will regenerate the "custom-cutscene-files" folder again will all demo files.
2. when you set reload assets to true, it will take any files in "custom-cutscene-files" and will make a custom mod containing all your images, sounds, and translations, called custom_cutscene_files.jar.
   (if nothing is in your "custom-cutscene-files" folder when you set reload assets, than it will build an empty jar, hence will give you a error.)

Now normally if you missing the config files and the custom-cutscene-files folder. It will regenerate all the Demo files. But if you add your own files you have to have them in "custom-cutscene-files"  and than reload assets so it creates the custom jar file. When you start the game, all the images and sounds are pulled from that custom jar it builds. When you add all your images and sounds you only have to reload assets that one time, unless you add more files. 

Eventually this process will be easier. This mod may be a WIP for a while, but as time goes on, I want to make this easier.

**Comment by EthanO3O** [comment]
sorry  i was just a little busy this time
i will try it when i back to my computer room (win 10)
:)
